version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: littlelemon
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
